language: python
python:
- '3.5'
- '3.6'
fail_fast: true
install:
- python setup.py install
- pip install pycodestyle
- pip install coveralls
- pip install environs
before_install:
- pip install --upgrade pip

script:
- find . -name \*.py -exec pycodestyle --ignore=E402,W504 {} +
- python -m unittest -v
- coverage run --source=. --omit=setup.py -m unittest -v

after_success:
- coveralls

env:
  global:
  - secure: GvQBynFlT08vmdv+6dni+YfZFrSrP1cH0gcJ4Bb/JpKhoMFDwBzszToomf8ZAJljRkFQz/1cfw/nK/1jk1llboOnr5c29Wuo8v1CMms+iRVbqhMGr4N8qexLaodWo5Irh9oyyRjEBFgZcsQyxZCxRWqb/XV0cGuI3YU9P5MbtlGPstVBZiJl92azn1phvsY++TFYeWP8bVebyU15hMSvz8YC8ERr3z5XKjPh6DgNTS0emM0al0j/X1Xd9AXU5nm4lCwIKH+7C8ynGtdOJ2f4cgGZNaVpnR4pYjZGWf9AIg29fgGeqyZVDyvJsUl1UtCMZOapGsyBQ7GHMAdq7Hwk3XW+vjZpHGk58h7txl0RbjdzJJEn+eSo37QLx7k/Jvbf+zfvPUOTMehToREZ57nRZdsq0/mURJ8q0RGLGNnaCEJmNdJupadOe18A2gc6EWRbdJbXTdqikCjS01WfpNCXS2hjnOzds37B0I2DJ8d0n9+ZYJRvgBZMYuI5nhf6ly9LeVAI5juRuKtXb4pAHE80ON3zUDSx009SByr9RDYn8kf1w6dXrMXJaudXljRh8kSUKNIvlBDlAgHp3/h4AWD/nyTnY8Za10PryAi8gJYlMvUJnM4yb0ZF7dHZRCcl77vR+m2Dr71ZSYJ/Rg/ac9P/1XbhVrXC5X30OAXYT8FhYMQ=
  - secure: RyqY8f6DIAqPttY4U7KWw71jVmbuS7/IzFjI+rEomEzRelmVgaGUqUdMipCvG/90bLqms4vpu9HCjEpG8Hm1tFn1zZZSOrExZk7m0nuwTrBMp6jCmRcAhvPwKE04LFuF9dzef8fLheUqyIAntM0kYEQ53NIQhJEC7rQeAfO4rUvVsEAoo/CllCtQ8vEJUTkfYA/67vB4naEfRbRasTNpj1Aon/LOuz1MaMUgMZCcCTRGN+GT/8HziLDWy6axKMzcZV24NWzGxFz1BSIcvTSEcEkASC/4Clj1+eINOP6VRa76lh3iEx+ogaWBSMwFMNfA3EGJbiO6sr8GEN962fgHMmjeCcdVLMmmUIDnhv4fATbmhwJ3V/kHPQ1kt9D9mWdjKNr4zZlT2cQC8bMmkYjFdikUqlWshlaTuTWZ3FcoGDARzJWtRoJpM8bIS0TroPwSKEUD4MNr6iU54sNFkadTI3xJ9rfooGQ1qXc/hRSUKiSyhkd9gO9EX8Zlhc8TvVQHvK35BGR1iLZXQ1Qx8jHASmAGTPyCfBePAIG6hPjl4Eu1geVtC69N/h97Tp5pORSQHr17Zx51Wfca75kwsyAH4vSpZFqC0fEWUSaz3WSyTCIPhwYNV9vn8R7Sy3Ol1GNNuJdkvMYC1fmwFk7Bd1O+YhAuRUnQkvFhk1P5Cn7YlHI=
  - secure: k6sdxjiowkeq6id8cRwg9T046OS4vpQ6fD5X2aq5BfHiLQo4RkZE1O5hsYsGrcvpQF30Iy+ZGc1exTlZWNOwtUQr5rYDYDk1pGsUlJotqXL08v+I6nXbj6fyBIpkuenpPB74+p1PjRX0LWJDJ31Asg3LbKVQTSXl8e2pGrU5CPAvBkuWAssSiS4nnK60vx6AWKpyrK4ZZjmcN5cgS6Xl9Z78f1UJDz0iMHsIhXo17ep3ui4Qlatxyr0JGuHvW+L/6mM99ye/90R6G8Xi364SllmVCBOKTJft4EVgm4ihc2Hw6OtjVuzZdVFteJZPioqlgVZtq01oxcR6vFfFzOqCxrzpZZja3iJ/7NMwuBdtmfzF64HketQqRbVerHgDAOwHZzF715xRdEudBPOV5URTMV8Oyol/XP+tCAXX8E7mXvnO6P384dw1hKpesH8YMQDHSpP9T2h6IZa6J53wwjoG6RRXJBfQQTsUOCLBHGL0afiPIC7X8MdFOL7D4ERkhJS+xmLeb2TZHQjYf8TuACDlVJjYc1oYFelOiS6Mrkm7Fq6RakG6zXSoZjyjC9NhXbivcL16EtRPpvufk7RvdSp+Z0PzcYojb+CvOfSYbuzbnNcAimPygfoq3AY4hZ3SPeD6Z2pR23b5ArR3PJ2MVSgNimUub/f2EFghFRxN39I/+EI=
  - API_VERSION='v1'